# Generated by Django 3.1.3 on 2020-11-07 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollOffensive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offensive_sentence', models.CharField(blank=True, max_length=400, null=True)),
                ('vote_yes', models.IntegerField(blank=True, null=True)),
                ('vote_no', models.IntegerField(blank=True, null=True)),
                ('voter_pole', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
